spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: springbootkotlin

---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://${MDB_USERNAME}:${MDB_PASSWORD}@172.17.0.1:27017