spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: springbootkotlin

cloud:
  aws:
    credentials:
      accessKey: <accessKey>
      secretKey: <secretKey>
    region: us-east-1
    endpoint: sqs.ap-us-1.amazonaws.com
    messageGroup: default
    messageQueue: <queue name>

---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://${MDB_USERNAME}:${MDB_PASSWORD}@172.17.0.1:27017